version: "3"

networks:
  backend:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "php-fpm-rs-task"
    volumes:
      - .:/app
      - ./conf/php-fpm-custom.ini:/usr/local/etc/php/conf.d/php-fpm-custom.ini
    networks:
      - backend

  nginx-back:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: "nginx-back-rs-task"
    ports:
      - "8081:80"
    depends_on:
      - php
    volumes:
      - .:/app/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/access.log:/log/access.log
      - ./nginx/error.log:/log/error.log
    networks:
      - backend
